version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "20:00"
      timezone: "Pacific/Honolulu"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "20:00"
      timezone: "Pacific/Honolulu"
    open-pull-requests-limit: 10
    target-branch: "devrc-2-5-0"