language: java
install: true
jdk:
  - oraclejdk8

dist: trusty

branches:
  only:
  - master

script:
  - mvn -Denv=dev clean test

after_success:
  - mvn jacoco:report coveralls:report

notifications:
  email:
    recipients:
      - its-iam-web-app-dev-help-l@lists.hawaii.edu
    on_success: change
    on_failure: always
