name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#dist:trusty is equivalent to runs on ubuntu
jobs:
  build:
    runs-on: [ ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -Denv=dev clean test

      - name: Jacoco report
        if: success()
        run: mvn jacoco:report coveralls:report
        